// Categories
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_FULFILLED = "GET_CATEGORIES_FULFILLED";

export const GET_CATEGORIES_ARTICLES = "GET_CATEGORIES_ARTICLES";
export const GET_CATEGORIES_ARTICLES_FULFILLED =
  "GET_CATEGORIES_ARTICLES_FULFILLED";

export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_FULFILLED = "GET_ARTICLES_FULFILLED";

export const GET_DETAIL_ARTICLES = "GET_DETAIL_ARTICLES";
export const GET_DETAIL_ARTICLES_FULFILLED = "GET_DETAIL_ARTICLES_FULFILLED";

export const GET_ARTICLES_BY_CATEGORIES = "GET_ARTICLES_BY_CATEGORIES";
export const GET_ARTICLES_BY_CATEGORIES_FULFILLED =
  "GET_ARTICLES_BY_CATEGORIES_FULFILLED";

export const LOGIN = "LOGIN";
